FROM alpine:3.17
MAINTAINER Matthew Horwood <matt@horwood.biz>

# Install required deb packages
RUN apk update && apk upgrade && \
    apk add php81-json php81-curl git php81 php81-phar php81-xml php81-tokenizer \
    php81-sockets curl php81-openssl php81-mbstring php81-dom php81-xmlwriter \
    && rm -f /var/cache/apk/*; \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer;

COPY . /foxess-mqtt
WORKDIR /foxess-mqtt
RUN composer install;
VOLUME /foxess-mqtt/data
CMD ["/foxess-mqtt/run.sh"]
