version: "2.1"

volumes:
  redis_data:
  foxess_data:

services:
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

  foxess-mqtt:
    image: mhzawadi/foxess-mqtt:latest
    container_name: foxess-mqtt
    restart: unless-stopped
    volumes:
      - foxess_data:/foxess-mqtt/data
    environment:
      - TIMEZONE=Europe/London
