FROM alpine:3.19
MAINTAINER Matthew Horwood <matt@horwood.biz>

# Install required deb packages
RUN apk update && apk upgrade && \
    apk add php82-json php82-curl git php82 php82-phar php82-xml php82-tokenizer \
    php82-sockets curl php82-openssl php82-mbstring php82-dom php82-xmlwriter \
    && rm -f /var/cache/apk/*; \
    php82 -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php82 composer-setup.php && \
    php82 -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer;

COPY . /foxess-mqtt
WORKDIR /foxess-mqtt
RUN composer install;
VOLUME /foxess-mqtt/data
CMD ["/foxess-mqtt/run.sh"]
