name: build our image for a version

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Prepare
        id: prepare
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo ::set-output name=version::${VERSION}
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mhzawadi/foxess-mqtt:${{ steps.prepare.outputs.version }}
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
